apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gocalc-ingress
  namespace: go-calc
spec:
  rules:
    - host: go.calc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-calc
                port:
                  number: 8080

